#!/bin/sh
set -eu

mkdir -p /data/oh-my-pi
if [ ! -e /data/oh-my-pi/agent/extensions ] && [ ! -L /data/oh-my-pi/agent/extensions ]; then
	ln -s "$HOME/.config/omp/extensions" /data/oh-my-pi/agent/extensions 2>/dev/null \
		|| [ -e /data/oh-my-pi/agent/extensions ] \
		|| [ -L /data/oh-my-pi/agent/extensions ]
fi

export PI_CONFIG_DIR=../../data/oh-my-pi
export PI_CONFIG_FILES="$HOME/.config/omp/shared.yml"
exec /usr/local/bin/omp "$@"
