#!/bin/sh

scripts_dir=$HOME/infra-template/cnc-shared/scripts/cnc

run_host() {
	sh "$scripts_dir/run-host" "$@"
}

run_host_root() {
	sh "$scripts_dir/run-host-root" "$@"
}

run_host journalctl -u cnc-build -f -n 0 -o cat &
journal_pid=$!
sleep 0.1

run_host_root systemctl --job-mode=ignore-dependencies restart cnc-build
restart_status=$?

kill "$journal_pid" 2>/dev/null
wait "$journal_pid" 2>/dev/null

if [ "$restart_status" -ne 0 ]; then
	exit "$restart_status"
fi

printf '\nBuild succeeded. Restarting cnc will delete data. Continue? [y/N] ' >/dev/tty
IFS= read -r answer </dev/tty

case $answer in
	y | Y | yes | YES | Yes)
		run_host_root systemctl --no-block restart cnc
		;;
esac
