protocols {
  imap = yes
  lmtp = no
  sieve = no
  submission = no
}

ssl = no
auth_allow_cleartext = yes

mail_driver = maildir
mail_path = /srv/vmail
mailbox_list_layout = fs

namespace inbox {
  inbox = yes
  separator = /

  mailbox "gmail main" {
    auto = subscribe
  }
  mailbox "gmail qa" {
    auto = subscribe
  }
  mailbox icloud {
    auto = subscribe
  }
}
