#!/bin/sh
set -eu

case ${1-} in
	systemctl)
		shift
		set -- /usr/bin/systemctl --machine=.host "$@"
		;;
esac

exec sudo nsenter \
	--uts=/host/proc/1/ns/uts \
	--ipc=/host/proc/1/ns/ipc \
	--net=/host/proc/1/ns/net \
	-- \
	chroot /host /usr/bin/env -i \
		TERM="${TERM:-xterm-256color}" \
		SYSTEMD_PAGER="${SYSTEMD_PAGER:-cat}" \
		HOME=/root \
		USER=root \
		LOGNAME=root \
		SHELL=/bin/bash \
		PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin \
		"$@"
