ports:
  dns: 53

upstreams:
  groups:
    default:
      - https://cloudflare-dns.com/dns-query
      - https://dns.google/dns-query

blocking:
  denylists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/popupads.txt
      - /app/additional_deny.txt
  allowlists:
    ads:
      - https://raw.githubusercontent.com/anudeepND/whitelist/refs/heads/master/domains/whitelist.txt
      - /app/additional_allow.txt
  clientGroupsBlock:
    default:
      - ads

queryLog:
  type: csv
  target: /logs
  logRetentionDays: 7
  flushInterval: 30s

hostsFile:
  sources:
    - http://host.containers.internal:16932/hosts
  hostsTTL: 5m
  loading:
    strategy: fast
    refreshPeriod: 1m
