# forward the active program's title
set -g set-titles on
set -g set-titles-string '#{pane_title}'

# preserve keys such as Ctrl+Backspace for terminal applications
set -s extended-keys on
set -as terminal-features ',xterm*:extkeys'
